name: "Run Tests"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-8.0-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-8.0-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress"

      - name: "Install laravel"
        run: "composer global require laravel/installer"

#      - name: Setup upterm session
#        uses: lhotari/action-upterm@v1

      - run: |
              sed -i "s/\$process->setTty(true);/\/\/\$process->setTty(true);/g" ./vendor/laravel/installer/src/NewCommand.php &&
              ./dokku-laravel new --force project1 project1
      - run: "cd project1"
      - run: "php artisan serve &"
      - run: "curl -s 127.0.0.1:8000"
      - run: "(curl -s 127.0.0.1:8000 | grep Laravel) || false"
      - run: "docker-compose up -d"
      - run: "php artisan migrate"
      - run: |
             echo '<?php echo App\Models\User::count(); ?> users' > resources/views/welcome.blade.php;
      - run: "curl -s 127.0.0.1:8000;"
      - run: "(curl -s 127.0.0.1:8000 | grep '0 users') || false;"