name: "Run Tests"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-8.0-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-8.0-composer-locked-"

#      - name: "Install dependencies with composer"
#        run: "composer install --no-interaction --no-progress"
